function mexCompile()
    % must include the GSL libraries
    % The -ffast-math improves speed
    
    % For stl pinhole plate and sample
    mex CFLAGS='$CFLAGS -I mtwister' mexFiles/tracingMex.c mexFiles/trace_ray.c ...
        mexFiles/tracing_functions.c ...
        mexFiles/scattering3D.c          mexFiles/scattering_processes3D.c ...
        mexFiles/ray_tracing_structs3D.c mexFiles/small_functions3D.c ...
        mexFiles/common_helpers.c mtwister/mtwister.c
    mex CFLAGS='$CFLAGS -I mtwister' mexFiles/tracingGenMex.c         mexFiles/trace_ray.c ...
        mexFiles/tracing_functions.c ...
        mexFiles/scattering3D.c          mexFiles/scattering_processes3D.c ...
        mexFiles/ray_tracing_structs3D.c mexFiles/small_functions3D.c ...
        mexFiles/common_helpers.c mtwister/mtwister.c
    
    % For a simple model of the pinhole plate
    mex CFLAGS='$CFLAGS -I mtwister' mexFiles/tracingMultiMex.c   mexFiles/trace_ray.c ...
        mexFiles/tracing_functions.c ...
        mexFiles/scattering3D.c          mexFiles/scattering_processes3D.c ...
        mexFiles/ray_tracing_structs3D.c mexFiles/small_functions3D.c ...
        mexFiles/common_helpers.c mtwister/mtwister.c
    mex CFLAGS='$CFLAGS -I mtwister' mexFiles/tracingMultiGenMex.c   mexFiles/trace_ray.c ...
        mexFiles/tracing_functions.c ...
        mexFiles/scattering3D.c          mexFiles/scattering_processes3D.c ...
        mexFiles/ray_tracing_structs3D.c mexFiles/small_functions3D.c ...
        mexFiles/common_helpers.c mtwister/mtwister.c
    
    % For distribution or trac scattering just off a sample
    mex CFLAGS='$CFLAGS -I mtwister' mexFiles/distributionCalcMex.c   mexFiles/trace_ray.c ...
        mexFiles/tracing_functions.c ...
        mexFiles/scattering3D.c          mexFiles/scattering_processes3D.c ...
        mexFiles/ray_tracing_structs3D.c mexFiles/small_functions3D.c ...
        mexFiles/common_helpers.c mtwister/mtwister.c
        
    % A binning function I wrote.
    mex mexFiles/binMyWayMex.c
end

