function minCompile()
    % compile and link minimal version of the code
    mex -R2018a -lgsl -lm -lgslcblas CFLAGS="\$CFLAGS -Wall -std=c99" ...
        mexFiles/tracingMultiGenMex.c ...
        mexFiles/common_helpers.c ...
        mexFiles/ray_tracing_structs3D.c ...
        mexFiles/extract_inputs.c ...
        mexFiles/small_functions3D.c ...
        mexFiles/distributions.c
end