function minCompile()
    % compile and link minimal version of the code
    mex -g -R2018a -lgsl -lm -lgslcblas CFLAGS="\$CFLAGS -Wall -std=c99" ...
        mexFiles/tracingMultiGenMex.c ...
        mexFiles/common_helpers.c ...
        mexFiles/ray_tracing_structs3D.c
end