function compile_tests()
    % compile and link files needed for testing
    mex -R2018a -lgsl -lm -lgslcblas -ImexFiles ...
        CFLAGS="\$CFLAGS -Wall -std=c99" ...
            test/mex/distribution_test_mex.c ...
            mexFiles/small_functions3D.c ...
            mexFiles/distributions.c ...
            mexFiles/ray_tracing_structs3D.c ...
            mexFiles/common_helpers.c ...
            mexFiles/extract_inputs.c
end
