addpath('import_3d/stlread', 'import_3d/objread', 'functions', ...
        'functions/interface_functions', 'classes', ...
        'mexFiles', 'DylanMuir-ParforProgMon-a80c9e9', 'functions/standard_samples', ...
        'surf2stl', 'experiments', 'experiments/help_functions');